{
  buildGoApplication,
  globs,
  lib,
  runCommand,
  generated,
  scaffolded,
}:
let
  fs = lib.fileset;

  repoSrc = fs.toSource {
    root = ../.;
    fileset = globs ../. [
      "go.mod"
      "go.sum"
      "**/*.go"
    ];
  };

  merged = runCommand "terraform-provider-pfsense-src" { } ''
    cp -rT ${repoSrc} $out
    chmod -R +w $out

    # Overlay generated schema packages (provider_pfsense/, resource_firewall_rule/)
    cp -rT ${generated} $out

    # Place scaffold output into resource package directory (with generated header)
    mkdir -p $out/resource_firewall_rule
    printf '// Code generated by tfplugingen-framework scaffold; DO NOT EDIT.\n\n' \
      > $out/resource_firewall_rule/firewall_rule_resource.go
    cat ${scaffolded}/firewall_rule_resource.go \
      >> $out/resource_firewall_rule/firewall_rule_resource.go
  '';
in
buildGoApplication {
  pname = "terraform-provider-pfsense";
  version = "0.1.0";
  modules = ./gomod2nix.toml;
  src = merged;
  subPackages = [ "cmd/terraform-provider-pfsense" ];
  # Exclude repo stubs (//go:build !nix) in favour of generated/scaffold code
  buildFlags = [ "-tags=nix" ];
  ldflags = [
    "-w"
    "-s"
  ];
}
