package pkg

import (
	"context"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"

	"charm.land/log/v2"
	"github.com/unmango/go/world"
)

const codegenHeader = "// Code generated by nix; DO NOT EDIT."

func ExtractConfig(ctx context.Context, src, dest string) error {
	log := log.FromContext(ctx)
	os := world.FromContext(ctx).Os()

	log.Info("Opening internal/config/parse.go")
	// https://github.com/hashicorp/terraform-plugin-codegen-openapi/blob/main/internal/config/parse.go
	file, err := os.OpenInRoot(src, "internal/config/parse.go")
	if err != nil {
		return err
	}
	defer file.Close()

	log.Info("Parsing source")
	fset := token.NewFileSet()
	fnode, err := parser.ParseFile(fset, "config.go", file,
		parser.ParseComments|parser.SkipObjectResolution,
	)
	if err != nil {
		return err
	}

	log.Info("Adding codegen header")
	header := &ast.CommentGroup{
		List: []*ast.Comment{{
			Text:  codegenHeader,
			Slash: token.Pos(1), // Start of the file
		}},
	}

	comments := []*ast.CommentGroup{header}
	for _, group := range fnode.Comments {
		comments = append(comments, group)
	}
	fnode.Comments = comments

	log.Info("Creating output file")
	out, err := os.Create(dest)
	if err != nil {
		return err
	}
	defer out.Close()

	log.Info("Writing formatted output")
	return format.Node(out, fset, fnode)
}
