package pkg

import (
	"context"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"

	"github.com/unmango/go/world"
)

const codegenHeader = "// Code generated by go generate; DO NOT EDIT."

func ExtractConfig(ctx context.Context, src, dest string) error {
	os := world.FromContext(ctx).Os()

	// https://github.com/hashicorp/terraform-plugin-codegen-openapi/blob/main/internal/config/parse.go
	file, err := os.OpenInRoot(src, "internal/config/parse.go")
	if err != nil {
		return err
	}
	defer file.Close()

	fset := token.NewFileSet()
	fnode, err := parser.ParseFile(fset, "config.go", file,
		parser.ParseComments|parser.SkipObjectResolution,
	)
	if err != nil {
		return err
	}

	fnode.Comments = append(fnode.Comments, &ast.CommentGroup{
		List: []*ast.Comment{{
			Text:  codegenHeader,
			Slash: fnode.Package,
		}},
	})

	out, err := os.Create(dest)
	if err != nil {
		return err
	}
	defer out.Close()

	return format.Node(out, fset, fnode)
}
